package Views;

import java.awt.event.ActionListener;

/**
 *
 * @author Jeremy Hudson
 * 
 * Last updated 4-10-2019
 * 
 * This class adds listeners to the searchDB button, and returns author
 * name, ISBN and book title. This class is called in the BooksController.
 */
public class BookDatabaseView extends javax.swing.JFrame {

    /**
     * Creates new form BookDBView
     */
    public BookDatabaseView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchLocalDatabaseButton = new javax.swing.JButton();
        LibManageSys2 = new javax.swing.JPanel();
        searchDatabaseLbl = new javax.swing.JLabel();
        searchAuthorTxtFld = new javax.swing.JTextField();
        searchTitleTxtFld = new javax.swing.JTextField();
        searchISBNTxtFld = new javax.swing.JTextField();
        searchByISBNLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        searchLocalDatabaseButton.setText("Search Database");

        LibManageSys2.setBorder(javax.swing.BorderFactory.createTitledBorder("Library Management System"));

        searchDatabaseLbl.setText("Search database ");

        searchAuthorTxtFld.setText("Author Name");

        searchTitleTxtFld.setText("Title of Book");

        searchByISBNLbl.setText("Search by ISBN");

        javax.swing.GroupLayout LibManageSys2Layout = new javax.swing.GroupLayout(LibManageSys2);
        LibManageSys2.setLayout(LibManageSys2Layout);
        LibManageSys2Layout.setHorizontalGroup(
            LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LibManageSys2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LibManageSys2Layout.createSequentialGroup()
                        .addGroup(LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchAuthorTxtFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(searchTitleTxtFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(searchISBNTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 45, Short.MAX_VALUE))
                    .addGroup(LibManageSys2Layout.createSequentialGroup()
                        .addComponent(searchDatabaseLbl)
                        .addGap(106, 106, 106)
                        .addComponent(searchByISBNLbl)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        LibManageSys2Layout.setVerticalGroup(
            LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LibManageSys2Layout.createSequentialGroup()
                .addGroup(LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDatabaseLbl)
                    .addComponent(searchByISBNLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchAuthorTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchISBNTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTitleTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LibManageSys2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchLocalDatabaseButton)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LibManageSys2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(searchLocalDatabaseButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void searchDBListener(ActionListener _listenForSearch) {
        this.searchLocalDatabaseButton.addActionListener(_listenForSearch);
    }

    public String getAuthorName() {
        return this.searchAuthorTxtFld.getText();
    }

    public String getBookTitle() {
        return this.searchTitleTxtFld.getText();
    }

    public String getISBN() {
        return this.searchISBNTxtFld.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LibManageSys2;
    private javax.swing.JTextField searchAuthorTxtFld;
    private javax.swing.JLabel searchByISBNLbl;
    private javax.swing.JLabel searchDatabaseLbl;
    private javax.swing.JTextField searchISBNTxtFld;
    private javax.swing.JButton searchLocalDatabaseButton;
    private javax.swing.JTextField searchTitleTxtFld;
    // End of variables declaration//GEN-END:variables
}
