package Views;

import java.awt.event.ActionListener;

/**
 *
 * @author Jeremy Hudson
 *
 * Last modified 4-25-2019
 *
 * This class adds a listener to the button that will open the database search
 * view
 */
public class CustomerView extends javax.swing.JFrame {

    public CustomerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custViewLabel = new javax.swing.JLabel();
        custSearchDatabaseButton = new javax.swing.JButton();
        custBookSearchLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        custViewLabel.setText("Customer View");

        custSearchDatabaseButton.setText("Search Database");

        custBookSearchLbl.setText("Search book database:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(custViewLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(custBookSearchLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(custSearchDatabaseButton)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(custViewLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custBookSearchLbl)
                    .addComponent(custSearchDatabaseButton))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void databaseListener(ActionListener _listenForDatabase) {
        this.custSearchDatabaseButton.addActionListener(_listenForDatabase);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custBookSearchLbl;
    private javax.swing.JButton custSearchDatabaseButton;
    private javax.swing.JLabel custViewLabel;
    // End of variables declaration//GEN-END:variables
}
