package Views;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;

/**
 *
 * @author Jeremy Hudson
 *
 * Last updated 4-25-2019
 *
 * This class simply displays the info for an individual book after being passed
 * data from the BooksController
 */
public class IndividualBookView extends javax.swing.JFrame {

    /**
     * Creates new form IndividualBookView1
     */
    public IndividualBookView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        IndividualBookVewISBNTxtLbl = new javax.swing.JLabel();
        individualBookVewNamePlaceholderTxtLbl = new javax.swing.JLabel();
        individualBookVewAuthorPlaceholderTxtLbl = new javax.swing.JLabel();
        individualBookVewCategoryPlaceholderTxtLbl = new javax.swing.JLabel();
        individualBookVewISBNPlaceholderTxtLbl = new javax.swing.JLabel();
        IndividualBookViewBookNameTxtLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imagePlaceholderLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Book Category:");

        IndividualBookVewISBNTxtLbl.setText("Book ISBN / Identifier:");

        individualBookVewNamePlaceholderTxtLbl.setText("Book Name Placeholder");

        individualBookVewAuthorPlaceholderTxtLbl.setText("Book Author Placeholder");

        individualBookVewCategoryPlaceholderTxtLbl.setText("Book Category Placeholder");

        individualBookVewISBNPlaceholderTxtLbl.setText("Book ISBN Placeholder");

        IndividualBookViewBookNameTxtLbl.setText("Book Name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        jLabel10.setText("Individual Book View");

        jLabel2.setText("Book Author:");

        imagePlaceholderLbl.setText("Image Placeholder ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IndividualBookViewBookNameTxtLbl)
                            .addComponent(IndividualBookVewISBNTxtLbl)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(individualBookVewAuthorPlaceholderTxtLbl)
                            .addComponent(individualBookVewCategoryPlaceholderTxtLbl)
                            .addComponent(individualBookVewISBNPlaceholderTxtLbl)
                            .addComponent(individualBookVewNamePlaceholderTxtLbl)))
                    .addComponent(imagePlaceholderLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualBookViewBookNameTxtLbl)
                    .addComponent(individualBookVewNamePlaceholderTxtLbl))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(individualBookVewAuthorPlaceholderTxtLbl))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(individualBookVewCategoryPlaceholderTxtLbl))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualBookVewISBNTxtLbl)
                    .addComponent(individualBookVewISBNPlaceholderTxtLbl))
                .addGap(65, 65, 65)
                .addComponent(imagePlaceholderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setIndividualBookVewAuthorPlaceholderTxtLbl(String _IndividualBookVewAuthorPlaceholderTxtLbl) {
        this.individualBookVewAuthorPlaceholderTxtLbl.setText(_IndividualBookVewAuthorPlaceholderTxtLbl);
    }

    public void setIndividualBookVewCategoryPlaceholderTxtLbl(String _IndividualBookVewCategoryPlaceholderTxtLbl) {
        this.individualBookVewCategoryPlaceholderTxtLbl.setText(_IndividualBookVewCategoryPlaceholderTxtLbl);
    }

    public void setIndividualBookVewISBNPlaceholderTxtLbl(String _IndividualBookVewISBNPlaceholderTxtLbl) {
        this.individualBookVewISBNPlaceholderTxtLbl.setText(_IndividualBookVewISBNPlaceholderTxtLbl);
    }

    public void setIndividualBookVewNamePlaceholderTxtLbl(String _IndividualBookVewNamePlaceholderTxtLbl) {
        this.individualBookVewNamePlaceholderTxtLbl.setText(_IndividualBookVewNamePlaceholderTxtLbl);
    }

    public void setImagePlaceholderLbl(String _imageLink) throws MalformedURLException, IOException {
        this.imagePlaceholderLbl.setText("");
        try {
            BufferedImage img = ImageIO.read(new URL(_imageLink));
            this.imagePlaceholderLbl.setIcon(new javax.swing.ImageIcon(img));
        } catch (Exception e) {

        }

    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IndividualBookVewISBNTxtLbl;
    private javax.swing.JLabel IndividualBookViewBookNameTxtLbl;
    private javax.swing.JLabel imagePlaceholderLbl;
    private javax.swing.JLabel individualBookVewAuthorPlaceholderTxtLbl;
    private javax.swing.JLabel individualBookVewCategoryPlaceholderTxtLbl;
    private javax.swing.JLabel individualBookVewISBNPlaceholderTxtLbl;
    private javax.swing.JLabel individualBookVewNamePlaceholderTxtLbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
